FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD dock-my-devs-sample-app.jar /opt/dock-my-devs-sample-app/
EXPOSE 8080
WORKDIR /opt/dock-my-devs-sample-app/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "dock-my-devs-sample-app.jar"]
